### ISSUE TITLE
web3 sendTransaction and payable contract functions

### ISSUE THREAD

**Issue by bluebirdly** [Neufund/ledger-wallet-provider#18]
I've been trying to get web3.eth.sendTransaction() to work with ledger-wallet-provider. web3.eth.sign() works fine - my ledger is prompted to to sign the transaction. web3.eth.sendTransaction() and contract calls don't do anything however. 

Any ideas where I can start? or maybe a working example somewhere?

**Comment by banciur** [comment]
Hey, 
You could try to run e2e tests. They are working both in node and browser. We are not calling any contracts calls but `sendTransaction` is working.

**Comment by bluebirdly** [comment]
I keep getting:

TypeError: this.getNetworkId is not a function
    at LedgerWallet._callee6$
(webpack-internal:///./node_modules/ledger-wallet-provider/lib/LedgerWallet.js:416:29)
    at tryCatch
(webpack-internal:///./node_modules/regenerator-runtime/runtime.js:65:40)

on web3.eth.sendTransaction()

**Comment by Ellieutt** [comment]
I was having the same error, you have to specify the getNetworkId method in the constructor

```
import Web3 from 'web3';
import LedgerWalletFactory from 'ledger-wallet-provider';
import ProviderEngine from 'web3-provider-engine';
import RpcSubprovider from 'web3-provider-engine/subproviders/rpc';

const engine = new ProviderEngine();
const web3 = new Web3(engine);
const networkId = 4; // for rinkeby testnet
const LedgerWalletFactory = await LedgerWalletFactory(() => networkId, `44'/60'/0'/0`);
engine.addProvider(LedgerWalletFactory);
engine.addProvider(new RpcSubprovider({ rpcUrl }));
engine.start();
```

**Comment by banciur** [comment]
@bluebirdly Did it solve your problem? I will fix doc soon.

**Comment by bluebirdly** [comment]
Thank you. All works well now - both sendTransaction() and contract
function calls (payable or otherwise).
