### ISSUE TITLE
Modifying timeout

### ISSUE THREAD

**Issue by Ellieutt** [Neufund/ledger-wallet-provider#19]
Hi there,

I figured out ledger's timeout is set at 20sec with your library, which is kinda annoying because it occurs exactly before the tx's gas cost is displayed on the ledger's screen.

Is there a way to change the ledger's timeout by passing it as a parameter in the constructor ?

You should considered putting a 30sec timeout, same as MEW

**Comment by banciur** [comment]
Sorry not at this moment :(
