### ISSUE TITLE
not obtaining the same addresses as in MEW

### ISSUE THREAD

**Issue by Ellieutt** [Neufund/ledger-wallet-provider#20]
Hi there,

I'd like to specify a desired derivationPath when calling the constructor:
`ledgerWalletSubProvider = await LedgerWalletSubprovider(() => networkId, derivationPath);
`

But I never get the same addresses as with MEW when I pass a desired derivationPath.
Even the default path which is 44'/60'/0'/0 actually corresponds to the derivation path 44'/60'/0'  in MEW.

**Comment by TimDaub** [comment]
Have the same problem here. When I use "m/44'/60'/0'/0" manually on mycrypto I get the right key while I get another one if I do:

```const derivation = "44'/60'/0'/0";
var ledgerWalletSubProvider = await LedgerWalletSubproviderFactory(
  1,
  derivation
);
```

**Comment by banciur** [comment]
When obtaining addresses use `Your Custom Path` option and pass `m/44'/60'/1'` and `m/44'/60'/0'` dps. myetherwallet UI will display adresses for:
- `m/44'/60'/1/0`
- `m/44'/60'/1/1`
- `m/44'/60'/1/2`
etc
