### ISSUE TITLE
Can you set the gasPrice and gas limit for a Transaction?

### ISSUE THREAD

**Issue by antsankov** [Neufund/ledger-wallet-provider#23]
First of all, thank you for this library. I notice in all of the tests that you use requests of the format:
```
  await web3.eth.sendTransactionAsync({
    from: ledgerDp1Acc0,
    to: ganacheAcc2,
    value: web3.toWei(0.5, "ether")
  });
```
I've tried to use the field `gasPrice` and `gas` and noticed that my Ledger freezes up when I do this. I assume this is because it is currently unsupported. Is it possible to set these fields?

**Comment by banciur** [comment]
It should be possible I just ran test with following code and it worked
```
  await web3.eth.sendTransactionAsync({
    from: ledgerDp0Acc0,
    to: ganacheAcc1,
    value: web3.toWei(0.25, "ether"),
    gas: 220000,
    gasPrice: "20000000000"
  });
```
