### ISSUE TITLE
Problem with U2F

### ISSUE THREAD

**Issue by adamskrodzki** [Neufund/ledger-wallet-provider#30]
Hi, I've tried using Your library on Chrome browser

First I've got the error that U2F Extension is required
then I've get error from below:

factory loading
u2f-api.js:523 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('chrome-extension://kmendfapggjehodndflmmgagdbamhnfd') does not match the recipient window's origin ('null').
factory loaded
ledger NOT supported

```

const Web3Ledger = require('ledger-wallet-provider');
            var factory = Web3Ledger.default;
console.log('factory loading');
            factory().then((instance: any) => {
                console.log('factory loaded');
                if (instance.isSupported) {
                    console.log('ledger supported');
                    instance.getAccounts(console.log);
                }
                else{
                    console.log('ledger NOT supported');
                }
             });
```

I'm runing website giving the error on my localhost 
Error is thrown before promise is resolved

**Comment by TimDaub** [comment]
You need to run your application on https in the browser. For webpack for example use the option `--https` then U2F will be supported.
