### ISSUE TITLE
Reports a more than one ledger connected

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/ledger-wallet-provider#4]
The library reports this error even tough there are no nano's connected at all 
"Error: You can only have one ledger connection active at a time"

Because the error always shows up later, i suspect that it might be related with a timeout function. but not sure

**Comment by rudolfix** [comment]
This may only happen if there is a pending request in https://github.com/Neufund/ledger-wallet-provider/blob/master/src/LedgerWallet.js . Are you using it via web3 wallet provider? if so maybe you try to sign transaction before list of accounts is returned or you try to sign new transaction while previous one is being signed?

**Comment by Moejoe90** [comment]
Yes currently using web3-wallet-provider through web3-polyfill, everything is disabled basically only initializing the provider-engine adding ledger-wallet and starting the engine. 
The error show's up after sometime a couple if mins and keeps recurring.
