### ISSUE TITLE
No support for personal.signMessage?

### ISSUE THREAD

**Issue by eordano** [Neufund/ledger-wallet-provider#7]
Hi all,

I'm wondering if there's a reason why signPersonalMessage is not implemented -- would that be something for which you would accept a pull request?

**Comment by banciur** [comment]
Hello @eordano 

It was our internal library and we didn't need it. But we are planing bigger overhaul in next two weeks and probably we will implement this functionality.

**Comment by 1blockologist** [comment]
Did you guys ever do this?

We use eth_signTypedData method

**Comment by banciur** [comment]
Not yet but its somewhere in our plans for future.

**Comment by 1blockologist** [comment]
okay EIP-712 is ratified now
